//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clay01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClayEntities : DbContext
    {
        public ClayEntities()
            : base("name=ClayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Door> Doors { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<HistoryLog> HistoryLogs { get; set; }
    
        public virtual ObjectResult<CP_GetHistoryLogs_Result> CP_GetHistoryLogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CP_GetHistoryLogs_Result>("CP_GetHistoryLogs");
        }
    
        public virtual ObjectResult<CP_GetDoorsByUserId_Result> CP_GetDoorsByUserId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CP_GetDoorsByUserId_Result>("CP_GetDoorsByUserId");
        }
    }
}
